# Generated by Django 6.0.3 on 2026-05-14 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0002_initial'),
        ('enrollments_app', '0002_initial'),
        ('progress_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.module'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.section'),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together={('student', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('student', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionprogress',
            unique_together={('student', 'section')},
        ),
    ]
