# Generated by Django 4.2.29 on 2026-03-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0002_initial'),
        ('enrollments_app', '0002_initial'),
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.content'),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together={('student', 'content')},
        ),
    ]
