# Generated by Django 4.2.11 on 2026-06-08 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress_app', '0001_initial'),
        ('enrollments_app', '0002_initial'),
        ('progress_app', '0001_initial'),
        ('courses_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.module'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses_app.content'),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='enrollments_app.enrollment'),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sectionprogress',
            unique_together={('student', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('student', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together={('student', 'content')},
        ),
    ]
