# Generated by Django 4.2.11 on 2026-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'permissions': [('view_progress', 'Can view progress'), ('change_progress', 'Can change progress')]},
        ),
    ]
