# Generated by Django 4.2.11 on 2026-05-28 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='started_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='last_updated'),
        ),
    ]
