# Generated by Django 6.0.3 on 2026-05-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0002_initial'),
    ]

    operations = [
    ]
