# Generated by Django 4.2.11 on 2026-08-10 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_content_draft_key_concept_cards_and_more'),
        ('enrollments_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptCardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_index', models.PositiveIntegerField()),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_card_progress', to='courses_app.content')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concept_card_progress', to='enrollments_app.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_card_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'content', 'card_index')},
            },
        ),
    ]
