# Generated by Django 4.2.11 on 2026-06-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'permissions': [('view_progress', 'Can view progress'), ('change_progress', 'Can change progress'), ('complete_progress', 'Can complete progress')]},
        ),
    ]
