# Generated by Django 4.2.11 on 2026-03-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments_app', '0002_initial'),
        ('progress_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprogress',
            name='enrollment',                    # add this
            
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='enrollments_app.enrollment'),
        ),
    ]
