# Generated by Django 4.2.11 on 2026-03-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments_app', '0002_initial'),
        ('progress_app', '0003_contentprogress_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='enrollment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='enrollments_app.enrollment'),
        ),
    ]
