# Generated by Django 4.2.11 on 2026-06-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0002_alter_courseprogress_options'),
        ('progress_app', '0003_courseprogress_created_at_and_more'),
    ]

    operations = [
    ]
