import { useState, useMemo, Fragment } from "react";
import { useData } from "../context/DataContext";
import { Card } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../components/ui/dialog";
import {
  Search,
  Download,
  AlertCircle,
  AlertTriangle,
  Info,
  Filter,
  Calendar,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

type ExportRange = "all" | "today" | "7d" | "30d" | "month" | "lastMonth" | "custom";
type ExportFormat = "csv" | "excel";

function filterByRange(logs: ReturnType<typeof useData>["auditLogs"], range: ExportRange, from: string, to: string) {
  if (range === "all") return logs;
  const now = new Date();
  const todayStr = now.toISOString().split("T")[0];
  const cutoff = (days: number) => {
    const d = new Date(now); d.setDate(d.getDate() - days);
    return d.toISOString().split("T")[0];
  };
  return logs.filter((l) => {
    const date = l.timestamp.split("T")[0];
    if (range === "today") return date === todayStr;
    if (range === "7d") return date >= cutoff(7);
    if (range === "30d") return date >= cutoff(30);
    if (range === "month") {
      const first = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split("T")[0];
      return date >= first;
    }
    if (range === "lastMonth") {
      const first = new Date(now.getFullYear(), now.getMonth() - 1, 1).toISOString().split("T")[0];
      const last = new Date(now.getFullYear(), now.getMonth(), 0).toISOString().split("T")[0];
      return date >= first && date <= last;
    }
    if (range === "custom") return (!from || date >= from) && (!to || date <= to);
    return true;
  });
}

function exportLogsCSV(logs: ReturnType<typeof useData>["auditLogs"], generatedBy: string, filterDesc: string) {
  const rows = [
    ["Generated By", generatedBy],
    ["Generated Date", new Date().toLocaleString()],
    ["Applied Filters", filterDesc],
    ["Record Count", String(logs.length)],
    [],
    ["Timestamp", "Actor", "Action", "Target", "Details", "IP Address", "Module", "Severity", "Status"],
    ...logs.map((l) => [
      new Date(l.timestamp).toLocaleString(),
      l.actor, l.action, l.target, l.details,
      l.ipAddress, l.module || "", l.severity, l.status,
    ]),
  ];
  const csv = rows.map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `audit-logs-${new Date().toISOString().split("T")[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportLogsExcel(logs: ReturnType<typeof useData>["auditLogs"], generatedBy: string, filterDesc: string) {
  const rows = [
    ["Generated By", generatedBy, "", "Generated Date", new Date().toLocaleString()],
    ["Applied Filters", filterDesc, "", "Record Count", String(logs.length)],
    [],
    ["Timestamp", "Actor", "Action", "Target", "Details", "IP Address", "Module", "Severity", "Status"],
    ...logs.map((l) => [
      new Date(l.timestamp).toLocaleString(),
      l.actor, l.action, l.target, l.details,
      l.ipAddress, l.module || "", l.severity, l.status,
    ]),
  ];
  const tsv = rows.map((r) => r.join("\t")).join("\n");
  const blob = new Blob([tsv], { type: "application/vnd.ms-excel" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `audit-logs-${new Date().toISOString().split("T")[0]}.xls`;
  a.click();
  URL.revokeObjectURL(url);
}

export function AuditLogsPage() {
  const { auditLogs } = useData();

  const [searchQuery, setSearchQuery] = useState("");
  const [severityFilter, setSeverityFilter] = useState("all");
  const [moduleFilter, setModuleFilter] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [showFilters, setShowFilters] = useState(false);
  const [expandedLog, setExpandedLog] = useState<number | null>(null);

  const [showExportDialog, setShowExportDialog] = useState(false);
  const [exportRange, setExportRange] = useState<ExportRange>("30d");
  const [exportFrom, setExportFrom] = useState("");
  const [exportTo, setExportTo] = useState("");
  const [exportFormat, setExportFormat] = useState<ExportFormat>("csv");

  const modules = useMemo(() => {
    const mods = new Set(auditLogs.map((l) => l.module).filter(Boolean));
    return Array.from(mods);
  }, [auditLogs]);

  const filteredLogs = useMemo(() => {
    return auditLogs.filter((log) => {
      const q = searchQuery.toLowerCase();
      const matchesSearch =
        log.actor.toLowerCase().includes(q) ||
        log.action.toLowerCase().includes(q) ||
        log.target.toLowerCase().includes(q) ||
        log.details.toLowerCase().includes(q);
      const matchesSeverity = severityFilter === "all" || log.severity === severityFilter;
      const matchesModule = moduleFilter === "all" || log.module === moduleFilter;
      const logDate = log.timestamp.split("T")[0];
      const matchesFrom = !dateFrom || logDate >= dateFrom;
      const matchesTo = !dateTo || logDate <= dateTo;
      return matchesSearch && matchesSeverity && matchesModule && matchesFrom && matchesTo;
    });
  }, [auditLogs, searchQuery, severityFilter, moduleFilter, dateFrom, dateTo]);

  const criticalCount = auditLogs.filter((l) => l.severity === "critical").length;
  const warningCount = auditLogs.filter((l) => l.severity === "warning").length;
  const infoCount = auditLogs.filter((l) => l.severity === "info").length;

  const getSeverityBadge = (severity: string) => {
    if (severity === "critical")
      return <Badge variant="destructive" className="gap-1"><AlertCircle className="w-3 h-3" />Critical</Badge>;
    if (severity === "warning")
      return <Badge variant="secondary" className="bg-yellow-100 text-yellow-800 gap-1"><AlertTriangle className="w-3 h-3" />Warning</Badge>;
    return <Badge variant="secondary" className="bg-blue-100 text-blue-800 gap-1"><Info className="w-3 h-3" />Info</Badge>;
  };

  const getStatusBadge = (status: string) => {
    if (status === "success") return <Badge className="bg-green-100 text-green-800">Success</Badge>;
    if (status === "warning") return <Badge className="bg-yellow-100 text-yellow-800">Warning</Badge>;
    if (status === "critical") return <Badge variant="destructive">Critical</Badge>;
    return <Badge variant="secondary">{status}</Badge>;
  };

  const handleExport = () => {
    const rangeFiltered = filterByRange(filteredLogs, exportRange, exportFrom, exportTo);
    const rangeLabel: Record<ExportRange, string> = {
      all: "All Time", today: "Today", "7d": "Last 7 Days", "30d": "Last 30 Days",
      month: "This Month", lastMonth: "Last Month", custom: `${exportFrom} to ${exportTo}`,
    };
    const filterDesc = `Severity: ${severityFilter}, Module: ${moduleFilter}, Date: ${rangeLabel[exportRange]}`;
    if (exportFormat === "csv") exportLogsCSV(rangeFiltered, "Current Admin", filterDesc);
    else exportLogsExcel(rangeFiltered, "Current Admin", filterDesc);
    setShowExportDialog(false);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">Audit Logs</h1>
          <p className="text-gray-500 mt-1">Comprehensive security event trail across all platform modules</p>
        </div>
        <Button onClick={() => setShowExportDialog(true)} className="gap-2">
          <Download className="w-4 h-4" />
          Export Logs
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Total Events", value: auditLogs.length, icon: <Info className="w-5 h-5 text-blue-600" />, bg: "bg-blue-50" },
          { label: "Critical", value: criticalCount, icon: <AlertCircle className="w-5 h-5 text-red-600" />, bg: "bg-red-50" },
          { label: "Warnings", value: warningCount, icon: <AlertTriangle className="w-5 h-5 text-yellow-600" />, bg: "bg-yellow-50" },
          { label: "Info", value: infoCount, icon: <Info className="w-5 h-5 text-blue-500" />, bg: "bg-blue-50" },
        ].map((s) => (
          <Card key={s.label} className="p-4">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-lg ${s.bg}`}>{s.icon}</div>
              <div>
                <p className="text-sm text-gray-500">{s.label}</p>
                <p className="text-2xl font-semibold text-gray-900">{s.value}</p>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Table + Filters */}
      <Card className="p-6">
        <div className="space-y-3 mb-5">
          <div className="flex flex-col md:flex-row gap-3">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <Input
                placeholder="Search by actor, action, target, or details..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={severityFilter} onValueChange={setSeverityFilter}>
              <SelectTrigger className="w-[160px]">
                <SelectValue placeholder="Severity" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Severity</SelectItem>
                <SelectItem value="critical">Critical</SelectItem>
                <SelectItem value="warning">Warning</SelectItem>
                <SelectItem value="info">Info</SelectItem>
              </SelectContent>
            </Select>
            <Select value={moduleFilter} onValueChange={setModuleFilter}>
              <SelectTrigger className="w-[160px]">
                <SelectValue placeholder="Module" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Modules</SelectItem>
                {modules.map((m) => <SelectItem key={m} value={m!}>{m}</SelectItem>)}
              </SelectContent>
            </Select>
            <Button
              variant="outline"
              className="gap-2"
              onClick={() => setShowFilters(!showFilters)}
            >
              <Filter className="w-4 h-4" />
              Date Range
              {showFilters ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            </Button>
          </div>

          {showFilters && (
            <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg border border-gray-100">
              <Calendar className="w-4 h-4 text-gray-500 shrink-0" />
              <div className="flex items-center gap-2 flex-wrap">
                <label className="text-xs font-medium text-gray-600">From</label>
                <Input
                  type="date"
                  value={dateFrom}
                  onChange={(e) => setDateFrom(e.target.value)}
                  className="w-40 h-8 text-sm"
                />
                <label className="text-xs font-medium text-gray-600">To</label>
                <Input
                  type="date"
                  value={dateTo}
                  onChange={(e) => setDateTo(e.target.value)}
                  className="w-40 h-8 text-sm"
                />
                {(dateFrom || dateTo) && (
                  <Button size="sm" variant="ghost" className="h-8 text-xs" onClick={() => { setDateFrom(""); setDateTo(""); }}>
                    Clear
                  </Button>
                )}
              </div>
            </div>
          )}
        </div>

        <div className="rounded-lg border overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-gray-50">
                <TableHead className="w-40">Timestamp</TableHead>
                <TableHead>Actor</TableHead>
                <TableHead>Action</TableHead>
                <TableHead>Target</TableHead>
                <TableHead>Module</TableHead>
                <TableHead>IP Address</TableHead>
                <TableHead>Severity</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredLogs.map((log) => (
                <Fragment key={log.id}>
                  <TableRow
                    className="cursor-pointer hover:bg-gray-50 transition-colors"
                    onClick={() => setExpandedLog(expandedLog === log.id ? null : log.id)}
                  >
                    <TableCell>
                      <p className="text-xs text-gray-600">
                        {new Date(log.timestamp).toLocaleDateString()}
                      </p>
                      <p className="text-xs text-gray-400">
                        {new Date(log.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                      </p>
                    </TableCell>
                    <TableCell>
                      <span className="text-sm font-medium text-gray-900">{log.actor}</span>
                    </TableCell>
                    <TableCell>
                      <span className="text-sm text-gray-700">{log.action}</span>
                    </TableCell>
                    <TableCell>
                      <span className="text-sm font-medium text-gray-900">{log.target}</span>
                    </TableCell>
                    <TableCell>
                      {log.module ? (
                        <Badge variant="secondary" className="text-xs">{log.module}</Badge>
                      ) : (
                        <span className="text-xs text-gray-400">—</span>
                      )}
                    </TableCell>
                    <TableCell>
                      <code className="text-xs px-2 py-1 bg-gray-100 rounded text-gray-700">
                        {log.ipAddress}
                      </code>
                    </TableCell>
                    <TableCell>{getSeverityBadge(log.severity)}</TableCell>
                    <TableCell>{getStatusBadge(log.status)}</TableCell>
                  </TableRow>
                  {expandedLog === log.id && (
                    <TableRow key={`${log.id}-expanded`}>
                      <TableCell colSpan={8} className="bg-gray-50 border-b border-gray-100">
                        <div className="px-2 py-3 space-y-2">
                          <p className="text-xs font-medium text-gray-700">Details</p>
                          <p className="text-sm text-gray-600">{log.details}</p>
                          {log.metadata && Object.keys(log.metadata).length > 0 && (
                            <div className="flex flex-wrap gap-3 mt-2">
                              {Object.entries(log.metadata).map(([k, v]) => (
                                <div key={k} className="text-xs">
                                  <span className="font-medium text-gray-500">{k}: </span>
                                  <span className="text-gray-700">{v}</span>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  )}
                </Fragment>
              ))}
            </TableBody>
          </Table>
        </div>

        {filteredLogs.length === 0 && (
          <div className="text-center py-16">
            <Filter className="w-10 h-10 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-500">No audit logs found matching your criteria</p>
            {(searchQuery || severityFilter !== "all" || moduleFilter !== "all" || dateFrom || dateTo) && (
              <Button
                variant="link"
                className="mt-2 text-blue-600"
                onClick={() => { setSearchQuery(""); setSeverityFilter("all"); setModuleFilter("all"); setDateFrom(""); setDateTo(""); }}
              >
                Clear all filters
              </Button>
            )}
          </div>
        )}

        <div className="mt-3 text-sm text-gray-500">
          Showing {filteredLogs.length} of {auditLogs.length} events
        </div>
      </Card>

      {/* Activity panels */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="p-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Recent Critical Events</h2>
          <div className="space-y-3">
            {auditLogs.filter((l) => l.severity === "critical").slice(0, 5).map((log) => (
              <div key={log.id} className="flex items-start gap-3 p-3 bg-red-50 rounded-lg border border-red-100">
                <AlertCircle className="w-4 h-4 text-red-600 mt-0.5 shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-sm font-medium text-gray-900">{log.actor}</span>
                    <span className="text-sm text-gray-600">{log.action}</span>
                  </div>
                  <p className="text-xs text-gray-600">
                    Target: <span className="font-medium">{log.target}</span>
                  </p>
                  <p className="text-xs text-gray-500 mt-1">{log.details}</p>
                  <p className="text-xs text-gray-400 mt-1">{new Date(log.timestamp).toLocaleString()}</p>
                </div>
              </div>
            ))}
            {auditLogs.filter((l) => l.severity === "critical").length === 0 && (
              <div className="text-center py-8 text-gray-400 text-sm">No critical events recorded</div>
            )}
          </div>
        </Card>

        <Card className="p-6">
          <h2 className="text-base font-semibold text-gray-900 mb-4">Activity Timeline</h2>
          <div className="space-y-4">
            {auditLogs.slice(0, 8).map((log, index) => (
              <div key={log.id} className="flex gap-3">
                <div className="flex flex-col items-center">
                  <div className={`w-2 h-2 rounded-full mt-1 shrink-0 ${
                    log.severity === "critical" ? "bg-red-500" :
                    log.severity === "warning" ? "bg-yellow-500" : "bg-blue-500"
                  }`} />
                  {index < 7 && <div className="w-px flex-1 bg-gray-200 my-1" />}
                </div>
                <div className="flex-1 pb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-gray-900">{log.actor}</span>
                    <span className="text-xs text-gray-500">{log.action}</span>
                    {log.module && <Badge variant="secondary" className="text-xs h-4">{log.module}</Badge>}
                  </div>
                  <p className="text-xs text-gray-500 mt-0.5">{log.details}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{new Date(log.timestamp).toLocaleString()}</p>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* Export Dialog */}
      <Dialog open={showExportDialog} onOpenChange={setShowExportDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Download className="w-5 h-5 text-blue-600" />
              Export Audit Logs
            </DialogTitle>
            <DialogDescription>
              Configure export settings. Metadata (generated by, date, filters) will be included.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <div>
              <label className="text-xs font-medium text-gray-700 mb-2 block">Date Range</label>
              <Select value={exportRange} onValueChange={(v) => setExportRange(v as ExportRange)}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Time</SelectItem>
                  <SelectItem value="today">Today</SelectItem>
                  <SelectItem value="7d">Last 7 Days</SelectItem>
                  <SelectItem value="30d">Last 30 Days</SelectItem>
                  <SelectItem value="month">This Month</SelectItem>
                  <SelectItem value="lastMonth">Last Month</SelectItem>
                  <SelectItem value="custom">Custom Range</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {exportRange === "custom" && (
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700 mb-1 block">From</label>
                  <Input type="date" value={exportFrom} onChange={(e) => setExportFrom(e.target.value)} />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700 mb-1 block">To</label>
                  <Input type="date" value={exportTo} onChange={(e) => setExportTo(e.target.value)} />
                </div>
              </div>
            )}

            <div>
              <label className="text-xs font-medium text-gray-700 mb-2 block">Format</label>
              <div className="flex gap-3">
                {(["csv", "excel"] as ExportFormat[]).map((fmt) => (
                  <button
                    key={fmt}
                    onClick={() => setExportFormat(fmt)}
                    className={`flex-1 py-2.5 px-4 rounded-lg border text-sm font-medium transition-colors ${
                      exportFormat === fmt
                        ? "border-blue-600 bg-blue-50 text-blue-700"
                        : "border-gray-200 text-gray-600 hover:border-gray-300"
                    }`}
                  >
                    {fmt.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>

            <div className="p-3 bg-gray-50 rounded-lg text-xs text-gray-600 space-y-1">
              <p className="font-medium text-gray-700">Export metadata includes:</p>
              <p>• Generated By: Current Admin</p>
              <p>• Institution: LearnHub Platform</p>
              <p>• Active Filters: Severity={severityFilter}, Module={moduleFilter}</p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowExportDialog(false)}>Cancel</Button>
            <Button onClick={handleExport} className="gap-2">
              <Download className="w-4 h-4" /> Export Now
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
