import { useState, useMemo } from "react";
import { useData, User } from "../context/DataContext";
import { toast } from "sonner";
import { useAppDispatch } from "../../hooks/reduxHooks";
import { createRBACUser, fetchRBACData } from "../../features/rbac/rbacSlice";
import { Card } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import { Avatar, AvatarFallback } from "../components/ui/avatar";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "../components/ui/sheet";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../components/ui/tabs";
import { Separator } from "../components/ui/separator";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "../components/ui/tooltip";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "../components/ui/dropdown-menu";
import {
  Search,
  UserPlus,
  MoreVertical,
  Shield,
  Activity,
  Building2,
  Download,
  ChevronRight,
  UserCheck,
  UserX,
  Key,
  Clock,
  AlertTriangle,
  CheckCircle,
  Eye,
  Trash2,
  Lock,
  Plus,
  History,
  Loader2,
} from "lucide-react";

// ─── Export helpers ──────────────────────────────────────────────────────────
type ExportRange = "today" | "7d" | "30d" | "month" | "lastMonth" | "custom";
type ExportFormat = "csv" | "excel";

function filterByRange(users: User[], range: ExportRange, from: string, to: string): User[] {
  const now = new Date();
  const todayStr = now.toISOString().split("T")[0];
  const cutoff = (days: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() - days);
    return d.toISOString().split("T")[0];
  };
  return users.filter((u) => {
    const created = u.createdAt.split("T")[0];
    if (range === "today") return created === todayStr;
    if (range === "7d") return created >= cutoff(7);
    if (range === "30d") return created >= cutoff(30);
    if (range === "month") {
      const first = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split("T")[0];
      return created >= first;
    }
    if (range === "lastMonth") {
      const first = new Date(now.getFullYear(), now.getMonth() - 1, 1).toISOString().split("T")[0];
      const last = new Date(now.getFullYear(), now.getMonth(), 0).toISOString().split("T")[0];
      return created >= first && created <= last;
    }
    if (range === "custom") return (!from || created >= from) && (!to || created <= to);
    return true;
  });
}

function exportToCSV(users: User[], generatedBy: string, filters: string) {
  const rows = [
    ["Generated By", generatedBy],
    ["Generated Date", new Date().toLocaleString()],
    ["Applied Filters", filters],
    ["Record Count", String(users.length)],
    [],
    ["Name", "Email", "Institution", "Department", "Roles", "Status", "Last Login", "Created"],
    ...users.map((u) => [
      u.name, u.email, u.institution, u.department || "", u.roles.join("; "), u.status, u.lastLogin, u.createdAt,
    ]),
  ];
  const csv = rows.map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `users-export-${new Date().toISOString().split("T")[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportToExcel(users: User[], generatedBy: string, filters: string) {
  // TSV-based Excel-compatible export
  const rows = [
    ["Generated By", generatedBy, "", "Generated Date", new Date().toLocaleString()],
    ["Applied Filters", filters, "", "Record Count", String(users.length)],
    [],
    ["Name", "Email", "Institution", "Department", "Roles", "Status", "Last Login", "Created"],
    ...users.map((u) => [
      u.name, u.email, u.institution, u.department || "", u.roles.join("; "), u.status, u.lastLogin, u.createdAt,
    ]),
  ];
  const tsv = rows.map((r) => r.join("\t")).join("\n");
  const blob = new Blob([tsv], { type: "application/vnd.ms-excel" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `users-export-${new Date().toISOString().split("T")[0]}.xls`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Permission-gated action button ──────────────────────────────────────────
function PermissionGate({
  allowed,
  label,
  children,
}: {
  allowed: boolean;
  label: string;
  children: React.ReactNode;
}) {
  if (allowed) return <>{children}</>;
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className="cursor-not-allowed opacity-50">{children}</span>
        </TooltipTrigger>
        <TooltipContent side="left" className="text-xs">
          <Lock className="w-3 h-3 inline mr-1" />
          {label}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────
export function UsersManagementPage() {
  const dispatch = useAppDispatch();
  const {
    users,
    roles,
    institutions,
    addUser,
    updateUser,
    deleteUser,
    assignRole,
    removeRole,
    getUserPermissions,
    addInstitution,
  } = useData();

  // Table filters
  const [searchQuery, setSearchQuery] = useState("");
  const [roleFilter, setRoleFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  // Selected user state
  const [selectedUser, setSelectedUser] = useState<User | null>(null);
  const [showUserDrawer, setShowUserDrawer] = useState(false);

  // Dialogs
  const [showAddUserDialog, setShowAddUserDialog] = useState(false);
  const [showAssignRoleDialog, setShowAssignRoleDialog] = useState(false);
  const [showRemoveRoleDialog, setShowRemoveRoleDialog] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [showExportDialog, setShowExportDialog] = useState(false);

  // Add user form
  const [addMode, setAddMode] = useState<"search" | "manual">("search");
  const [learnerSearch, setLearnerSearch] = useState("");
  const [newUserForm, setNewUserForm] = useState({
    name: "", email: "", institution: "", department: "", role: "",
  });
  const [newInstitutionName, setNewInstitutionName] = useState("");
  const [showNewInstitution, setShowNewInstitution] = useState(false);
  const [addUserErrors, setAddUserErrors] = useState<Record<string, string>>({});
  const [isAddingUser, setIsAddingUser] = useState(false);

  // Role assign
  const [selectedRole, setSelectedRole] = useState("");
  const [roleToRemove, setRoleToRemove] = useState("");

  // Export
  const [exportRange, setExportRange] = useState<ExportRange>("30d");
  const [exportFrom, setExportFrom] = useState("");
  const [exportTo, setExportTo] = useState("");
  const [exportFormat, setExportFormat] = useState<ExportFormat>("csv");

  // Filtered table
  const filteredUsers = useMemo(() =>
    users.filter((user) => {
      const q = searchQuery.toLowerCase();
      const matchesSearch =
        user.name.toLowerCase().includes(q) ||
        user.email.toLowerCase().includes(q) ||
        user.institution.toLowerCase().includes(q);
      const matchesRole = roleFilter === "all" || user.roles.includes(roleFilter);
      const matchesStatus = statusFilter === "all" || user.status === statusFilter;
      return matchesSearch && matchesRole && matchesStatus;
    }),
    [users, searchQuery, roleFilter, statusFilter]
  );

  // Derived data for selected user
  const userPermissions = selectedUser ? getUserPermissions(selectedUser.id) : [];
  const permissionsByModule = useMemo(() => {
    const map: Record<string, string[]> = {};
    userPermissions.forEach((p) => {
      const mod = p.split(".")[0];
      if (!map[mod]) map[mod] = [];
      map[mod].push(p);
    });
    return map;
  }, [userPermissions]);

  // Role assignment diff
  const selectedRoleObj = roles.find((r) => r.name === selectedRole);
  const currentPerms = selectedUser ? getUserPermissions(selectedUser.id) : [];
  const newPermsGained = selectedRoleObj
    ? selectedRoleObj.permissions.filter((p) => !currentPerms.includes(p))
    : [];

  // Learner search for "existing user" mode (use users list as source)
  const matchedLearners = useMemo<User[]>(
    () =>
      learnerSearch.length >= 2
        ? users.filter((l: User) =>
          l.name.toLowerCase().includes(learnerSearch.toLowerCase()) ||
          l.email.toLowerCase().includes(learnerSearch.toLowerCase())
        )
        : [],
    [users, learnerSearch]
  );

  // ─── Handlers ───────────────────────────────────────────────────────────────
  const handleViewUser = (user: User) => {
    setSelectedUser(user);
    setShowUserDrawer(true);
  };

  const syncSelectedUser = (id: number) => {
    const updated = users.find((u) => u.id === id);
    if (updated) setSelectedUser(updated);
  };

  const handleAssignRole = async () => {
    if (selectedUser && selectedRole) {
      const id = toast.loading("Assigning role...");
      try {
        await assignRole(selectedUser.id, selectedRole);
        toast.success("Role assigned", { id });
      } catch (err: any) {
        toast.error(err?.message || "Failed to assign role", { id });
      }
      setShowAssignRoleDialog(false);
      setSelectedRole("");
      syncSelectedUser(selectedUser.id);
    }
  };

  const handleRemoveRole = async () => {
    if (selectedUser && roleToRemove) {
      const id = toast.loading("Removing role...");
      try {
        await removeRole(selectedUser.id, roleToRemove);
        toast.success("Role removed", { id });
      } catch (err: any) {
        toast.error(err?.message || "Failed to remove role", { id });
      }
      setShowRemoveRoleDialog(false);
      setRoleToRemove("");
      syncSelectedUser(selectedUser.id);
    }
  };

  const handleDeleteUser = async () => {
    if (selectedUser) {
      const id = toast.loading("Deleting user...");
      try {
        await deleteUser(selectedUser.id);
        toast.success("User deleted", { id });
      } catch (err: any) {
        toast.error(err?.message || "Failed to delete user", { id });
      }
      setShowDeleteDialog(false);
      setShowUserDrawer(false);
      setSelectedUser(null);
    }
  };

  const validateAddUser = () => {
    const errs: Record<string, string> = {};
    if (!newUserForm.name.trim()) errs.name = "Full name is required";
    if (!newUserForm.email.trim()) errs.email = "Email is required";
    else if (!/\S+@\S+\.\S+/.test(newUserForm.email)) errs.email = "Invalid email format";
    else if (users.some((u) => u.email === newUserForm.email)) errs.email = "Email already exists";
    if (!newUserForm.role) errs.role = "Role is required";
    if (!newUserForm.institution.trim()) errs.institution = "Institution is required";
    return errs;
  };

  const handleAddUser = async () => {
    const errs = validateAddUser();
    if (Object.keys(errs).length > 0) { setAddUserErrors(errs); return; }

    setIsAddingUser(true);
    const toastId = toast.loading("Creating user...");

    try {
      await dispatch(
        createRBACUser({
          name: newUserForm.name,
          email: newUserForm.email,
          institution: newUserForm.institution,
          department: newUserForm.department,
          role: newUserForm.role,
        })
      ).unwrap();

      toast.success("User created successfully! Invite email sent.", { id: toastId });
      setShowAddUserDialog(false);
      resetAddForm();
    } catch (error: any) {
      const message = error?.message || error?.detail || "Failed to create user";
      toast.error(message, { id: toastId });
    } finally {
      setIsAddingUser(false);
    }
  };

  const handleSelectLearner = (learner: User) => {
    setNewUserForm({
      name: learner.name,
      email: learner.email,
      institution: learner.institution || "",
      department: "",
      role: "",
    });
    setLearnerSearch("");
    setAddMode("manual");
  };

  const handleAddInstitution = () => {
    if (!newInstitutionName.trim()) return;
    addInstitution({ name: newInstitutionName, domain: "", status: "active" });
    setNewUserForm((f) => ({ ...f, institution: newInstitutionName }));
    setNewInstitutionName("");
    setShowNewInstitution(false);
  };

  const resetAddForm = () => {
    setNewUserForm({ name: "", email: "", institution: "", department: "", role: "" });
    setAddUserErrors({});
    setAddMode("search");
    setLearnerSearch("");
  };

  const handleExport = () => {
    const rangeFiltered = filterByRange(filteredUsers, exportRange, exportFrom, exportTo);
    const rangeLabel = { today: "Today", "7d": "Last 7 Days", "30d": "Last 30 Days", month: "This Month", lastMonth: "Last Month", custom: `${exportFrom} to ${exportTo}` }[exportRange];
    const filterDesc = `Role: ${roleFilter}, Status: ${statusFilter}, Date: ${rangeLabel}`;
    if (exportFormat === "csv") exportToCSV(rangeFiltered, "Current Admin", filterDesc);
    else exportToExcel(rangeFiltered, "Current Admin", filterDesc);
    setShowExportDialog(false);
  };

  const handleActivateUser = async (user: User) => {
    const id = toast.loading(user.status === "active" ? "Deactivating user..." : "Activating user...");
    try {
      // Use the context-provided updateUser function which handles dispatch internally
      await updateUser(user.id, { status: user.status === "active" ? "inactive" : "active" });
      // Refresh the entire RBAC data to ensure the table reflects the new status immediately
      await dispatch(fetchRBACData());
      toast.success(user.status === "active" ? "User deactivated" : "User activated", { id });
    } catch (err: any) {
      toast.error(err?.message || "Failed to change status", { id });
    }
    syncSelectedUser(user.id);
  };

  // ─── Render ──────────────────────────────────────────────────────────────────
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">User Management</h1>
          <p className="text-gray-500 mt-1">Manage user accounts, roles, and access rights</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" className="gap-2" onClick={() => setShowExportDialog(true)}>
            <Download className="w-4 h-4" />
            Export
          </Button>
          <Button className="gap-2" onClick={() => { resetAddForm(); setShowAddUserDialog(true); }}>
            <UserPlus className="w-4 h-4" />
            Add User
          </Button>
        </div>
      </div>

      {/* Stats strip */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Total Users", value: users.length, icon: <UserCheck className="w-5 h-5 text-blue-600" />, bg: "bg-blue-50" },
          { label: "Active", value: users.filter(u => u.status === "active").length, icon: <CheckCircle className="w-5 h-5 text-green-600" />, bg: "bg-green-50" },
          { label: "Inactive", value: users.filter(u => u.status === "inactive").length, icon: <UserX className="w-5 h-5 text-gray-500" />, bg: "bg-gray-50" },
          { label: "Roles", value: roles.length, icon: <Shield className="w-5 h-5 text-purple-600" />, bg: "bg-purple-50" },
        ].map((stat) => (
          <Card key={stat.label} className="p-4">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-lg ${stat.bg}`}>{stat.icon}</div>
              <div>
                <p className="text-sm text-gray-500">{stat.label}</p>
                <p className="text-2xl font-semibold text-gray-900">{stat.value}</p>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Table */}
      <Card className="p-6">
        <div className="flex flex-col md:flex-row gap-3 mb-5">
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              placeholder="Search by name, email, or institution..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>
          <Select value={roleFilter} onValueChange={setRoleFilter}>
            <SelectTrigger className="w-[180px]">
              <SelectValue placeholder="Filter by role" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Roles</SelectItem>
              {roles.map((role) => (
                <SelectItem key={role.id} value={role.name}>{role.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[160px]">
              <SelectValue placeholder="Filter by status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Status</SelectItem>
              <SelectItem value="active">Active</SelectItem>
              <SelectItem value="inactive">Inactive</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="rounded-lg border overflow-hidden">
          <Table>
            <TableHeader>
              <TableRow className="bg-gray-50">
                <TableHead>User</TableHead>
                <TableHead>Institution</TableHead>
                <TableHead>Roles</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Last Login</TableHead>
                <TableHead>Member Since</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredUsers.map((user) => (
                <TableRow
                  key={user.id}
                  className="cursor-pointer hover:bg-gray-50 transition-colors"
                  onClick={() => handleViewUser(user)}
                >
                  <TableCell>
                    <div className="flex items-center gap-3">
                      <Avatar className="w-8 h-8">
                        <AvatarFallback className="bg-blue-100 text-blue-700 text-xs font-semibold">
                          {user.avatar}
                        </AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="font-medium text-gray-900 text-sm">{user.name}</p>
                        <p className="text-xs text-gray-500">{user.email}</p>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1.5">
                      <Building2 className="w-3.5 h-3.5 text-gray-400" />
                      <span className="text-sm text-gray-600">{user.institution}</span>
                    </div>
                  </TableCell>
                  <TableCell>
                    <div className="flex flex-wrap gap-1">
                      {user.roles.slice(0, 2).map((role) => (
                        <Badge key={role} variant="secondary" className="text-xs px-2">
                          {role}
                        </Badge>
                      ))}
                      {user.roles.length > 2 && (
                        <Badge variant="secondary" className="text-xs px-2">+{user.roles.length - 2}</Badge>
                      )}
                    </div>
                  </TableCell>
                  <TableCell onClick={(e) => e.stopPropagation()}>
                    <button
                      className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full transition-colors ${user.status === "active"
                        ? "bg-green-100 text-green-800 hover:bg-green-200"
                        : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                        }`}
                      onClick={() => handleActivateUser(user)}
                      title={`Click to ${user.status === "active" ? "deactivate" : "activate"}`}
                    >
                      <span className={`w-1.5 h-1.5 rounded-full ${user.status === "active" ? "bg-green-500" : "bg-gray-400"}`} />
                      {user.status === "active" ? "Active" : "Inactive"}
                    </button>
                  </TableCell>
                  <TableCell>
                    <span className="text-sm text-gray-500">{user.lastLogin}</span>
                  </TableCell>
                  <TableCell>
                    <span className="text-sm text-gray-500">{user.createdAt.split("T")[0]}</span>
                  </TableCell>
                  <TableCell className="text-right" onClick={(e) => e.stopPropagation()}>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                          <MoreVertical className="w-4 h-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end" className="w-48">
                        <DropdownMenuItem onClick={() => handleViewUser(user)} className="gap-2">
                          <Eye className="w-4 h-4" /> View Details
                        </DropdownMenuItem>
                        <DropdownMenuItem
                          onClick={() => { setSelectedUser(user); setShowAssignRoleDialog(true); }}
                          className="gap-2"
                        >
                          <Shield className="w-4 h-4" /> Assign Role
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleActivateUser(user)} className="gap-2">
                          {user.status === "active" ? <UserX className="w-4 h-4" /> : <UserCheck className="w-4 h-4" />}
                          {user.status === "active" ? "Deactivate" : "Activate"}
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                          onClick={() => { setSelectedUser(user); setShowDeleteDialog(true); }}
                          className="gap-2 text-red-600 focus:text-red-600"
                        >
                          <Trash2 className="w-4 h-4" /> Delete User
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>

        {filteredUsers.length === 0 && (
          <div className="text-center py-16">
            <UserX className="w-10 h-10 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-500">No users found matching your criteria</p>
          </div>
        )}

        <div className="mt-3 flex items-center justify-between text-sm text-gray-500">
          <span>{filteredUsers.length} of {users.length} users</span>
        </div>
      </Card>

      {/* ── User Details Drawer ─────────────────────────────────────── */}
      <Sheet open={showUserDrawer} onOpenChange={setShowUserDrawer}>
        <SheetContent className="sm:max-w-[520px] overflow-y-auto p-0">
          {selectedUser && (
            <>
              {/* Identity header */}
              <div className="bg-gradient-to-br from-blue-600 to-blue-700 px-6 py-8 text-white">
                <SheetHeader className="mb-4">
                  <SheetTitle className="text-white">User Profile</SheetTitle>
                </SheetHeader>
                <div className="flex items-center gap-4">
                  <Avatar className="w-16 h-16 border-2 border-white/30">
                    <AvatarFallback className="bg-white/20 text-white text-lg font-bold">
                      {selectedUser.avatar}
                    </AvatarFallback>
                  </Avatar>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-lg leading-tight">{selectedUser.name}</h3>
                    <p className="text-blue-100 text-sm truncate">{selectedUser.email}</p>
                    <div className="flex items-center gap-2 mt-2">
                      <span className={`inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full font-medium ${selectedUser.status === "active"
                        ? "bg-green-400/20 text-green-100"
                        : "bg-gray-400/20 text-gray-200"
                        }`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${selectedUser.status === "active" ? "bg-green-300" : "bg-gray-400"}`} />
                        {selectedUser.status === "active" ? "Active" : "Inactive"}
                      </span>
                      {selectedUser.department && (
                        <span className="text-xs text-blue-200">{selectedUser.department}</span>
                      )}
                    </div>
                  </div>
                </div>
                <div className="mt-4 flex items-center gap-1.5 text-blue-100 text-xs">
                  <Building2 className="w-3.5 h-3.5" />
                  {selectedUser.institution}
                </div>
              </div>

              {/* Tabs */}
              <Tabs defaultValue="access" className="flex-1">
                <TabsList className="w-full rounded-none border-b h-auto p-0 bg-white">
                  {["access", "activity", "security"].map((tab) => (
                    <TabsTrigger
                      key={tab}
                      value={tab}
                      className="flex-1 rounded-none py-3 text-xs font-medium capitalize data-[state=active]:border-b-2 data-[state=active]:border-blue-600 data-[state=active]:shadow-none"
                    >
                      {tab}
                    </TabsTrigger>
                  ))}
                </TabsList>

                {/* ACCESS TAB */}
                <TabsContent value="access" className="p-6 space-y-6 mt-0">
                  <div>
                    <div className="flex items-center justify-between mb-3">
                      <h4 className="text-sm font-semibold text-gray-900 flex items-center gap-2">
                        <Shield className="w-4 h-4 text-blue-600" />
                        Assigned Roles
                      </h4>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-7 text-xs gap-1"
                        onClick={() => setShowAssignRoleDialog(true)}
                      >
                        <Plus className="w-3 h-3" /> Assign
                      </Button>
                    </div>
                    {selectedUser.roles.length === 0 ? (
                      <p className="text-sm text-gray-400 italic">No roles assigned</p>
                    ) : (
                      <div className="space-y-2">
                        {selectedUser.roles.map((role) => {
                          const roleObj = roles.find((r) => r.name === role);
                          return (
                            <div key={role} className="flex items-center justify-between px-3 py-2 bg-blue-50 rounded-lg border border-blue-100">
                              <div className="flex items-center gap-2">
                                <Shield className="w-3.5 h-3.5 text-blue-600" />
                                <div>
                                  <p className="text-sm font-medium text-blue-900">{role}</p>
                                  {roleObj && <p className="text-xs text-blue-600">{roleObj.permissions.length} permissions</p>}
                                </div>
                              </div>
                              <button
                                className="text-xs text-red-500 hover:text-red-700 px-2 py-0.5 rounded hover:bg-red-50 transition-colors"
                                onClick={() => { setRoleToRemove(role); setShowRemoveRoleDialog(true); }}
                              >
                                Remove
                              </button>
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>

                  <Separator />

                  <div>
                    <h4 className="text-sm font-semibold text-gray-900 flex items-center gap-2 mb-3">
                      <Key className="w-4 h-4 text-orange-500" />
                      Effective Permissions
                      <Badge variant="secondary" className="text-xs ml-auto">{userPermissions.length}</Badge>
                    </h4>
                    {Object.keys(permissionsByModule).length === 0 ? (
                      <p className="text-sm text-gray-400 italic">No permissions</p>
                    ) : (
                      <div className="space-y-3 max-h-56 overflow-y-auto pr-1">
                        {Object.entries(permissionsByModule).map(([mod, perms]) => (
                          <div key={mod}>
                            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">{mod}</p>
                            <div className="flex flex-wrap gap-1">
                              {perms.map((p) => (
                                <span key={p} className="text-xs px-2 py-0.5 bg-orange-50 text-orange-700 rounded border border-orange-100">
                                  {p.split(".")[1]}
                                </span>
                              ))}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </TabsContent>

                {/* ACTIVITY TAB */}
                <TabsContent value="activity" className="p-6 space-y-5 mt-0">
                  <div className="grid grid-cols-2 gap-3">
                    <div className="p-3 bg-gray-50 rounded-lg">
                      <p className="text-xs text-gray-500 mb-1">Last Login</p>
                      <p className="text-sm font-medium text-gray-900">{selectedUser.lastLogin}</p>
                    </div>
                    <div className="p-3 bg-gray-50 rounded-lg">
                      <p className="text-xs text-gray-500 mb-1">Member Since</p>
                      <p className="text-sm font-medium text-gray-900">{selectedUser.createdAt.split("T")[0]}</p>
                    </div>
                  </div>

                  <div>
                    <h4 className="text-sm font-semibold text-gray-900 flex items-center gap-2 mb-3">
                      <Activity className="w-4 h-4 text-blue-600" />
                      Recent Actions
                    </h4>
                    {selectedUser.recentActivity.length === 0 ? (
                      <p className="text-sm text-gray-400 italic">No recent activity</p>
                    ) : (
                      <div className="space-y-2">
                        {selectedUser.recentActivity.map((activity, i) => (
                          <div key={i} className="flex items-start gap-3 py-2 border-b border-gray-50 last:border-0">
                            <div className="w-1.5 h-1.5 rounded-full bg-blue-400 mt-1.5 shrink-0" />
                            <p className="text-sm text-gray-600">{activity}</p>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </TabsContent>

                {/* SECURITY TAB */}
                <TabsContent value="security" className="p-6 space-y-5 mt-0">
                  <div>
                    <h4 className="text-sm font-semibold text-gray-900 flex items-center gap-2 mb-3">
                      <Clock className="w-4 h-4 text-gray-500" />
                      Activation History
                    </h4>
                    {!selectedUser.activationHistory?.length ? (
                      <p className="text-sm text-gray-400 italic">No status changes recorded</p>
                    ) : (
                      <div className="space-y-2">
                        {selectedUser.activationHistory.map((entry, i) => (
                          <div key={i} className="flex items-center justify-between py-2 border-b border-gray-50 last:border-0">
                            <div className="flex items-center gap-2">
                              {entry.action === "activated"
                                ? <UserCheck className="w-3.5 h-3.5 text-green-600" />
                                : <UserX className="w-3.5 h-3.5 text-red-500" />}
                              <span className="text-sm text-gray-700 capitalize">{entry.action}</span>
                            </div>
                            <div className="text-right">
                              <p className="text-xs text-gray-500">{entry.date}</p>
                              <p className="text-xs text-gray-400">by {entry.by}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <Separator />

                  <div>
                    <h4 className="text-sm font-semibold text-gray-900 flex items-center gap-2 mb-3">
                      <History className="w-4 h-4 text-gray-500" />
                      Role Assignment History
                    </h4>
                    {!selectedUser.roleHistory?.length ? (
                      <p className="text-sm text-gray-400 italic">No role changes recorded</p>
                    ) : (
                      <div className="space-y-2">
                        {selectedUser.roleHistory.slice().reverse().map((entry, i) => (
                          <div key={i} className="flex items-center justify-between py-2 border-b border-gray-50 last:border-0">
                            <div className="flex items-center gap-2">
                              <Badge
                                variant="secondary"
                                className={`text-xs ${entry.action === "assigned" ? "bg-green-100 text-green-800" : "bg-red-100 text-red-700"}`}
                              >
                                {entry.action}
                              </Badge>
                              <span className="text-sm text-gray-700">{entry.role}</span>
                            </div>
                            <div className="text-right">
                              <p className="text-xs text-gray-500">{entry.date}</p>
                              <p className="text-xs text-gray-400">by {entry.by}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <Separator />

                  <div className="space-y-2 pt-2">
                    <Button
                      variant="outline"
                      className="w-full text-sm gap-2"
                      onClick={() => selectedUser && handleActivateUser(selectedUser)}
                    >
                      {selectedUser.status === "active"
                        ? <><UserX className="w-4 h-4" />Deactivate Account</>
                        : <><UserCheck className="w-4 h-4" />Activate Account</>}
                    </Button>
                    <Button
                      variant="outline"
                      className="w-full text-sm text-red-600 hover:bg-red-50 border-red-200 gap-2"
                      onClick={() => setShowDeleteDialog(true)}
                    >
                      <Trash2 className="w-4 h-4" />
                      Delete User Account
                    </Button>
                  </div>
                </TabsContent>
              </Tabs>
            </>
          )}
        </SheetContent>
      </Sheet>

      {/* ── Add User Dialog ──────────────────────────────────────────── */}
      <Dialog open={showAddUserDialog} onOpenChange={(o) => { if (!o) resetAddForm(); setShowAddUserDialog(o); }}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <UserPlus className="w-5 h-5 text-blue-600" />
              Add New User
            </DialogTitle>
            <DialogDescription>
              Search for an existing platform user or create a new account manually.
            </DialogDescription>
          </DialogHeader>

          <Tabs value={addMode} onValueChange={(v) => setAddMode(v as "search" | "manual")}>
            <TabsList className="w-full">
              <TabsTrigger value="search" className="flex-1 gap-2">
                <Search className="w-3.5 h-3.5" /> Existing User
              </TabsTrigger>
              <TabsTrigger value="manual" className="flex-1 gap-2">
                <UserPlus className="w-3.5 h-3.5" /> Manual Entry
              </TabsTrigger>
            </TabsList>

            {/* Search existing learners */}
            <TabsContent value="search" className="mt-4 space-y-3">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <Input
                  placeholder="Search learners by name or email..."
                  value={learnerSearch}
                  onChange={(e) => setLearnerSearch(e.target.value)}
                  className="pl-10"
                />
              </div>
              {learnerSearch.length >= 2 && (
                <div className="border rounded-lg max-h-52 overflow-y-auto">
                  {matchedLearners.length === 0 ? (
                    <div className="p-4 text-center text-sm text-gray-500">No matching learners found</div>
                  ) : (
                    matchedLearners.map((learner) => (
                      <button
                        key={learner.id}
                        className="w-full flex items-center gap-3 px-4 py-3 hover:bg-blue-50 transition-colors border-b last:border-0"
                        onClick={() => handleSelectLearner(learner)}
                      >
                        <Avatar className="w-8 h-8">
                          <AvatarFallback className="bg-blue-100 text-blue-700 text-xs">{learner.avatar}</AvatarFallback>
                        </Avatar>
                        <div className="flex-1 text-left">
                          <p className="text-sm font-medium text-gray-900">{learner.name}</p>
                          <p className="text-xs text-gray-500">{learner.email}</p>
                        </div>
                        <ChevronRight className="w-4 h-4 text-gray-400" />
                      </button>
                    ))
                  )}
                </div>
              )}
              {learnerSearch.length < 2 && (
                <div className="text-center py-8 text-gray-400 text-sm">
                  Type at least 2 characters to search
                </div>
              )}
            </TabsContent>

            {/* Manual entry */}
            <TabsContent value="manual" className="mt-4 space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="col-span-2">
                  <label className="text-xs font-medium text-gray-700 mb-1 block">Full Name *</label>
                  <Input
                    placeholder="Jane Smith"
                    value={newUserForm.name}
                    onChange={(e) => setNewUserForm((f) => ({ ...f, name: e.target.value }))}
                    className={addUserErrors.name ? "border-red-400" : ""}
                  />
                  {addUserErrors.name && <p className="text-xs text-red-500 mt-1">{addUserErrors.name}</p>}
                </div>
                <div className="col-span-2">
                  <label className="text-xs font-medium text-gray-700 mb-1 block">Institutional Email *</label>
                  <Input
                    placeholder="jane@institution.edu"
                    type="email"
                    value={newUserForm.email}
                    onChange={(e) => setNewUserForm((f) => ({ ...f, email: e.target.value }))}
                    className={addUserErrors.email ? "border-red-400" : ""}
                  />
                  {addUserErrors.email && <p className="text-xs text-red-500 mt-1">{addUserErrors.email}</p>}
                </div>
                <div className="col-span-2">
                  <label className="text-xs font-medium text-gray-700 mb-1 block">Institution *</label>
                  {showNewInstitution ? (
                    <div className="flex gap-2">
                      <Input
                        placeholder="New institution name"
                        value={newInstitutionName}
                        onChange={(e) => setNewInstitutionName(e.target.value)}
                        className="flex-1"
                      />
                      <Button size="sm" onClick={handleAddInstitution}>Add</Button>
                      <Button size="sm" variant="ghost" onClick={() => setShowNewInstitution(false)}>×</Button>
                    </div>
                  ) : (
                    <div className="flex gap-2">
                      <Select
                        value={newUserForm.institution}
                        onValueChange={(v) => setNewUserForm((f) => ({ ...f, institution: v }))}
                      >
                        <SelectTrigger className={`flex-1 ${addUserErrors.institution ? "border-red-400" : ""}`}>
                          <SelectValue placeholder="Select institution" />
                        </SelectTrigger>
                        <SelectContent>
                          {institutions.filter(i => i.status === "active").map((inst) => (
                            <SelectItem key={`${inst.id}-${inst.name}`} value={inst.name}>{inst.name}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <Button
                        size="sm"
                        variant="outline"
                        className="shrink-0 gap-1"
                        onClick={() => setShowNewInstitution(true)}
                        title="Create new institution"
                      >
                        <Plus className="w-3.5 h-3.5" />
                      </Button>
                    </div>
                  )}
                  {addUserErrors.institution && <p className="text-xs text-red-500 mt-1">{addUserErrors.institution}</p>}
                </div>
                <div className="col-span-2">
                  <label className="text-xs font-medium text-gray-700 mb-1 block">Department</label>
                  <Input
                    placeholder="e.g. Engineering"
                    value={newUserForm.department}
                    onChange={(e) => setNewUserForm((f) => ({ ...f, department: e.target.value }))}
                  />
                </div>
                <div className="col-span-2">
                  <p className="text-xs text-gray-500">
                    New users are created inactive by default and invited to set their password through email.
                  </p>
                </div>
                <div className="col-span-2">
                  <label className="text-xs font-medium text-gray-700 mb-1 block">Role *</label>
                  <Select
                    value={newUserForm.role}
                    onValueChange={(v) => setNewUserForm((f) => ({ ...f, role: v }))}
                  >
                    <SelectTrigger className={addUserErrors.role ? "border-red-400" : ""}>
                      <SelectValue placeholder="Select a role" />
                    </SelectTrigger>
                    <SelectContent>
                      {roles.map((role) => (
                        <SelectItem key={role.id} value={role.name}>
                          <span className="font-medium">{role.name}</span>
                          <span className="text-gray-500 ml-2 text-xs">({role.permissions.length} permissions)</span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {addUserErrors.role && <p className="text-xs text-red-500 mt-1">{addUserErrors.role}</p>}
                </div>
              </div>
            </TabsContent>
          </Tabs>

          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => { resetAddForm(); setShowAddUserDialog(false); }} disabled={isAddingUser}>
              Cancel
            </Button>
            <Button onClick={handleAddUser} disabled={addMode === "search" || isAddingUser} className="gap-2">
              {isAddingUser ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" /> Creating...
                </>
              ) : (
                <>
                  <UserPlus className="w-4 h-4" /> Create User
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Assign Role Dialog ───────────────────────────────────────── */}
      <Dialog open={showAssignRoleDialog} onOpenChange={setShowAssignRoleDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Shield className="w-5 h-5 text-blue-600" />
              Assign Role
            </DialogTitle>
            <DialogDescription>
              Assigning a role to <strong>{selectedUser?.name}</strong> will grant the associated permissions.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <div>
              <label className="text-xs font-medium text-gray-700 mb-2 block">Select Role</label>
              <Select value={selectedRole} onValueChange={setSelectedRole}>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a role..." />
                </SelectTrigger>
                <SelectContent>
                  {roles
                    .filter((r) => !selectedUser?.roles.includes(r.name))
                    .map((role) => (
                      <SelectItem key={role.id} value={role.name}>
                        <span className="font-medium">{role.name}</span>
                        <span className="text-gray-500 ml-2 text-xs">({role.permissions.length} perms)</span>
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
            </div>

            {selectedRoleObj && (
              <div className="rounded-lg border bg-gray-50 p-4 space-y-3">
                <p className="text-xs font-semibold text-gray-700">Role Preview: {selectedRoleObj.name}</p>
                <p className="text-xs text-gray-500">{selectedRoleObj.description}</p>

                {newPermsGained.length > 0 && (
                  <div>
                    <p className="text-xs font-medium text-green-700 mb-1.5 flex items-center gap-1">
                      <CheckCircle className="w-3.5 h-3.5" />
                      {newPermsGained.length} new permissions will be granted
                    </p>
                    <div className="flex flex-wrap gap-1">
                      {newPermsGained.slice(0, 8).map((p) => (
                        <span key={p} className="text-xs px-2 py-0.5 bg-green-100 text-green-800 rounded">
                          {p}
                        </span>
                      ))}
                      {newPermsGained.length > 8 && (
                        <span className="text-xs px-2 py-0.5 bg-green-100 text-green-800 rounded">
                          +{newPermsGained.length - 8} more
                        </span>
                      )}
                    </div>
                  </div>
                )}

                {newPermsGained.length === 0 && (
                  <p className="text-xs text-gray-500 italic">All permissions in this role are already granted</p>
                )}

                {newPermsGained.length > 10 && (
                  <div className="flex items-start gap-2 p-2 bg-yellow-50 rounded border border-yellow-200">
                    <AlertTriangle className="w-4 h-4 text-yellow-600 shrink-0 mt-0.5" />
                    <p className="text-xs text-yellow-800">
                      This role grants a significant number of new permissions. Review carefully before confirming.
                    </p>
                  </div>
                )}
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => { setShowAssignRoleDialog(false); setSelectedRole(""); }}>
              Cancel
            </Button>
            <Button onClick={handleAssignRole} disabled={!selectedRole} className="gap-2">
              <Shield className="w-4 h-4" /> Confirm Assignment
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Remove Role Dialog ───────────────────────────────────────── */}
      <Dialog open={showRemoveRoleDialog} onOpenChange={setShowRemoveRoleDialog}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-red-600">
              <AlertTriangle className="w-5 h-5" />
              Remove Role
            </DialogTitle>
            <DialogDescription>
              Remove <strong>"{roleToRemove}"</strong> from <strong>{selectedUser?.name}</strong>?
              The associated permissions will be revoked.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowRemoveRoleDialog(false)}>Cancel</Button>
            <Button variant="destructive" onClick={handleRemoveRole} className="gap-2">
              <Trash2 className="w-4 h-4" /> Remove Role
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Delete User Dialog ───────────────────────────────────────── */}
      <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-red-600">
              <Trash2 className="w-5 h-5" />
              Delete User
            </DialogTitle>
            <DialogDescription>
              Permanently delete <strong>{selectedUser?.name}</strong>? This removes all access and cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDeleteDialog(false)}>Cancel</Button>
            <Button variant="destructive" onClick={handleDeleteUser}>Delete Permanently</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Export Dialog ────────────────────────────────────────────── */}
      <Dialog open={showExportDialog} onOpenChange={setShowExportDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Download className="w-5 h-5 text-blue-600" />
              Export Users
            </DialogTitle>
            <DialogDescription>
              Configure your export settings. Metadata will be included in the file header.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-2">
            <div>
              <label className="text-xs font-medium text-gray-700 mb-2 block">Date Range</label>
              <Select value={exportRange} onValueChange={(v) => setExportRange(v as ExportRange)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="today">Today</SelectItem>
                  <SelectItem value="7d">Last 7 Days</SelectItem>
                  <SelectItem value="30d">Last 30 Days</SelectItem>
                  <SelectItem value="month">This Month</SelectItem>
                  <SelectItem value="lastMonth">Last Month</SelectItem>
                  <SelectItem value="custom">Custom Range</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {exportRange === "custom" && (
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700 mb-1 block">From</label>
                  <Input type="date" value={exportFrom} onChange={(e) => setExportFrom(e.target.value)} />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700 mb-1 block">To</label>
                  <Input type="date" value={exportTo} onChange={(e) => setExportTo(e.target.value)} />
                </div>
              </div>
            )}

            <div>
              <label className="text-xs font-medium text-gray-700 mb-2 block">Format</label>
              <div className="flex gap-3">
                {(["csv", "excel"] as ExportFormat[]).map((fmt) => (
                  <button
                    key={fmt}
                    onClick={() => setExportFormat(fmt)}
                    className={`flex-1 py-2.5 px-4 rounded-lg border text-sm font-medium transition-colors ${exportFormat === fmt
                      ? "border-blue-600 bg-blue-50 text-blue-700"
                      : "border-gray-200 text-gray-600 hover:border-gray-300"
                      }`}
                  >
                    {fmt.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>

            <div className="p-3 bg-gray-50 rounded-lg text-xs text-gray-600 space-y-1">
              <p className="font-medium text-gray-700">Export will include:</p>
              <p>• Generated By: Current Admin</p>
              <p>• Applied Filters: Role={roleFilter}, Status={statusFilter}</p>
              <p>• Record count based on selected date range</p>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowExportDialog(false)}>Cancel</Button>
            <Button onClick={handleExport} className="gap-2">
              <Download className="w-4 h-4" /> Export Now
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
