# Generated by Django 6.0.3 on 2026-03-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
    ]
