# Generated by Django 6.0.3 on 2026-03-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20260316_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
