# Generated by Django 4.2.11 on 2026-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='draft_key_concept_cards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_key_concept_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_require_key_concept_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='key_concept_cards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='key_concept_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='require_key_concept_review',
            field=models.BooleanField(default=False),
        ),
    ]
