# Generated by Django 4.2.11 on 2026-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
