# Generated by Django 6.0.3 on 2026-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
