# Generated by Django 4.2.11 on 2026-03-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_alter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='Organizer',
        ),
    ]
