# Generated by Django 4.2.11 on 2026-05-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='draft_content_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('file', 'File'), ('text', 'Text'), ('shell', 'Shell')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_file',
            field=models.FileField(blank=True, null=True, upload_to='draft_content_files/'),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='draft_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_courses_category', to='courses_app.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_courses_level', to='courses_app.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='draft_course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='draft_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='draft_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='draft_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='draft_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='draft_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='draft_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
    ]
