# Generated by Django 4.2.11 on 2026-05-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_module_quiz_enabled'),
    ]

    operations = [
    ]
