# Generated by Django 6.0.3 on 2026-04-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_mediaupload_question_alter_lesson_unique_together_and_more'),
        ('progress_app', '0003_alter_contentprogress_enrollment_moduleprogress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
