# Generated by Django 4.2.11 on 2026-08-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_category_name_alter_level_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'permissions': [('publish_course', 'Can publish courses'), ('view_published_course', 'Can view published courses'), ('manage_meta', 'Can manage course metadata levels and categories')]},
        ),
    ]
