# Generated by Django 4.2.11 on 2026-03-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_rename_instructor_course_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Organizer',
            new_name='organizer',
        ),
    ]
