# Generated by Django 4.2.11 on 2026-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0003_assessment_assessmentquestion_assessmentchoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentchoice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="assessmentquestion",
            name="assessment",
        ),
        migrations.AddField(
            model_name="course",
            name="final_assessment",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("note", "Note"),
                    ("file", "File"),
                    ("image", "Image"),
                    ("quiz", "Quiz"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Assessment",
        ),
        migrations.DeleteModel(
            name="AssessmentChoice",
        ),
        migrations.DeleteModel(
            name="AssessmentQuestion",
        ),
    ]
