# Generated by Django 4.2.11 on 2026-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'permissions': [('publish_course', 'Can publish courses'), ('view_published_course', 'Can view published courses')]},
        ),
    ]
