# Generated by Django 6.0.3 on 2026-05-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_content_is_published_module_is_published_and_more'),
        ('courses_app', '0004_content_is_published_module_is_published_and_more'),
    ]

    operations = [
    ]
