# Generated by Django 4.2.11 on 2026-08-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_course_options'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE courses_app_section DROP COLUMN description",
            reverse_sql="ALTER TABLE courses_app_section ADD COLUMN description longtext NOT NULL DEFAULT ''"
        ),
    ]
