# Generated by Django 4.2.11 on 2026-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0004_remove_assessmentchoice_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("note", "Note"),
                    ("file", "File"),
                    ("quiz", "Quiz"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="final_assessment",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
