# Generated by Django 4.2.11 on 2026-08-18 10:30

from django.db import connection, migrations


def remove_section_description(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM courses_app_section LIKE %s", ['description'])
        if cursor.fetchone():
            cursor.execute("ALTER TABLE courses_app_section DROP COLUMN description")


def add_section_description(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM courses_app_section LIKE %s", ['description'])
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE courses_app_section ADD COLUMN description LONGTEXT NOT NULL DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_course_options'),
    ]

    operations = [
        migrations.RunPython(remove_section_description, add_section_description),
    ]
