# Generated by Django 6.0.3 on 2026-04-29 14:29

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_delete_lesson'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Module',
        #     fields=[
        #         ('id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('title', models.CharField(max_length=255)),
        #         ('description', models.TextField(blank=True)),
        #         ('order', models.PositiveIntegerField()),
        #         ('quiz', models.JSONField(blank=True, null=True)),
        #         ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course', related_name='modules')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Section',
        #     fields=[
        #         ('id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('title', models.CharField(max_length=255)),
        #         ('order', models.PositiveIntegerField()),
        #         ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.module', related_name='sections')),
        #     ],
        # ),
        # # migrations.CreateModel(
        #     name='Quiz',
        #     fields=[
        #         ('id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('title', models.CharField(max_length=255)),
        #         ('description', models.TextField(blank=True)),
        #         ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses_app.module', related_name='module_quiz')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Question',
        #     fields=[
        #         ('id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('text', models.TextField()),
        #         ('mark', models.PositiveIntegerField(default=1)),
        #         ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.quiz', related_name='questions')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.question', related_name='options')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='quiz_attempts')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.quiz', related_name='attempts')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.attempt', related_name='answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='courses_app.option', null=True, blank=True)),
            ],
        ),
    ]
