# Generated by Django 4.2.11 on 2026-09-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_content_draft_key_concept_cards_and_more'),
        ('courses_app', '0005_remove_section_description'),
    ]

    operations = [
    ]
