# Generated by Django 4.2.11 on 2026-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_app", "0005_alter_content_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="course_media/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
