# Generated by Django 4.2.11 on 2026-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_mediaupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('note', 'Note'), ('image', 'Image'), ('file', 'File'), ('quiz', 'Quiz')], max_length=20),
        ),
    ]
