# Generated by Django 6.0.3 on 2026-04-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_alter_attempt_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='final_assessment',
        ),
    ]
