# Generated by Django 6.0.3 on 2026-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0007_remove_course_final_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='note_text',
        ),
        migrations.AddField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_mark',
            field=models.IntegerField(default=70),
        ),
    ]
