# Generated by Django 4.2.29 on 2026-05-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0007_alter_content_content_type'),
        ('courses_app', '0007_remove_category_level_alter_content_content_type'),
    ]

    operations = [
    ]
