# Generated by Django 6.0.3 on 2026-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0008_remove_content_note_text_content_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
