# Generated by Django 6.0.3 on 2026-09-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate_app', '0002_initial'),
        ('enrollments_app', '0001_initial'),
        ('progress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='progress_app.courseprogress'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='enrollments_app.enrollment'),
        ),
    ]
