# Generated by Django 4.2.29 on 2026-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments_app', '0002_initial'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='enrollment',
    #         name='created_at',
    #     ),
    migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    
