# Generated by Django 4.2.11 on 2026-09-28 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0023_survey_assessment_duration_minutes_and_more'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('viewer', 'Viewer'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('training_user', 'Training User')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_users', to=settings.AUTH_USER_MODEL)),
                ('trainings', models.ManyToManyField(blank=True, related_name='training_users', to='assessments_app.training')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traininguserprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
