# Generated by Django 4.2.29 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("viewer", "Viewer"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
