# Generated by Django 4.2.11 on 2026-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('assign_role', 'Can assign roles'), ('modify_role', 'Can modify roles'), ('modify_permission', 'Can modify permissions'), ('view_analytics', 'Can view analytics'), ('change_platform_settings', 'Can change platform settings')]},
        ),
    ]
