# Generated by Django 4.2.11 on 2026-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_user_level_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('viewer', 'Viewer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
