# Generated by Django 6.0.3 on 2026-09-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydiscussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityreply',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community_app.communitydiscussion'),
        ),
        migrations.AddIndex(
            model_name='communitylike',
            index=models.Index(fields=['item_type', 'item_id'], name='community_a_item_ty_3d0695_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitylike',
            unique_together={('user', 'item_type', 'item_id')},
        ),
    ]
