# Generated by Django 4.2.11 on 2026-08-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitydiscussion',
            options={'ordering': ['-created_at'], 'permissions': [('change_discussion_status', 'Can change discussion status')]},
        ),
        migrations.AlterModelOptions(
            name='communitylike',
            options={'permissions': [('add_like', 'Can add like')]},
        ),
    ]
