# Generated by Django 4.2.29 on 2026-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
