# Generated by Django 6.0.3 on 2026-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
