# Generated by Django 4.2.11 on 2026-05-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='is_final',
        ),
    ]
