# Generated by Django 6.0.3 on 2026-09-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments_app', '0001_initial'),
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='attached_assessments', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses_app.module'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='attached_assessments', to='courses_app.module'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments_app.assessment'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='courses_app.course'),
        ),
    ]
