# Generated by Django 4.2.11 on 2026-05-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
