# Generated by Django 4.2.11 on 2026-05-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0002_remove_assessment_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
