# Generated by Django 4.2.11 on 2026-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0002_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
