# Generated by Django 4.2.11 on 2026-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0002_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
