# Generated by Django 4.2.11 on 2026-06-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': [('start_assessment', 'Can start assessment')]},
        ),
    ]
