# Generated by Django 4.2.11 on 2026-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='tab_switch_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tab_switch_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
