# Generated by Django 6.0.3 on 2026-05-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_assessment_is_published'),
        ('assessments_app', '0003_initial'),
    ]

    operations = [
    ]
