# Generated by Django 4.2.11 on 2026-06-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={},
        ),
    ]
