# Generated by Django 4.2.11 on 2026-04-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_rename_created_at_attempt_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
