# Generated by Django 4.2.11 on 2026-06-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at'], 'permissions': [('start_assessment', 'Can start assessment'), ('lock_attempt', 'Can lock attempt'), ('unlock_attempt', 'Can unlock attempt'), ('grade_assessment', 'Can grade assessment')]},
        ),
    ]
