# Generated by Django 4.2.29 on 2026-05-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0002_alter_attempt_options_attempt_is_locked'),
        ('assessments_app', '0004_assessment_duration_assessment_instructions_and_more'),
    ]

    operations = [
    ]
