# Generated by Django 4.2.11 on 2026-06-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0004_alter_assessment_options'),
        ('assessments_app', '0004_alter_attempt_options'),
    ]

    operations = [
    ]
