# Generated by Django 6.0.3 on 2026-05-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0004_merge_0003_assessment_is_published_0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
    ]
