# Generated by Django 4.2.11 on 2026-06-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0004_alter_assessment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'permissions': [('start_assessment', 'Can start assessment')]},
        ),
    ]
