# Generated by Django 4.2.11 on 2026-06-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0005_alter_assessment_options'),
        ('assessments_app', '0005_merge_20260611_1130'),
    ]

    operations = [
    ]
