# Generated by Django 4.2.29 on 2026-05-04 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0008_merge_20260504_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments_app', '0005_merge_20260504_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='courses_app.course'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments_app.assessment'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('student', 'assessment', 'attempt_number')},
        ),
    ]
