# Generated by Django 4.2.29 on 2026-05-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0006_rename_created_at_attempt_started_at_and_more'),
    ]

    operations = [
    ]
