# Generated by Django 4.2.11 on 2026-07-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('matching', 'Matching')], default='single', max_length=10),
        ),
    ]
