# Generated by Django 4.2.29 on 2026-05-04 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0007_auto_20260504_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
