# Generated by Django on 2026-08-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0006_merge_20260619_1016'),
        ('assessments_app', '0007_question_matching_pairs_alter_question_question_type'),
    ]

    operations = []
