# Generated by Django 4.2.29 on 2026-05-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0008_merge_20260504_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments_app', '0008_remove_attempt_created_at_attempt_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='next_allowed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments_app.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments_app.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_answers', to='assessments_app.choice')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='multi_answers', to='assessments_app.choice')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
