# Generated by Django 4.2.11 on 2026-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
        ('assessments_app', '0009_alter_assessment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='attached_assessments', to='courses_app.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='attached_assessments', to='courses_app.module'),
        ),
    ]
