# Generated by Django 4.2.11 on 2026-08-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0008_merge_20260805_1607'),
        ('assessments_app', '0010_assessment_courses_assessment_modules'),
    ]

    operations = [
    ]
