# Generated by Django 4.2.11 on 2026-08-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0008_merge_20260810_1731'),
        ('assessments_app', '0010_assessment_courses_assessment_modules'),
    ]

    operations = [
    ]
