# Generated by Django 4.2.11 on 2026-08-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0005_remove_section_description'),
        ('assessments_app', '0011_merge_20260818_1111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attempt',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='courses_app.course'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('student', 'assessment', 'attempt_number', 'course')},
        ),
    ]
