# Generated by Django 4.2.11 on 2026-08-19 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0005_remove_section_description'),
        ('assessments_app', '0012_alter_attempt_unique_together_attempt_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='draft_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_matching_pairs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='draft_question_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice'), ('matching', 'Matching')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='pending_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('student', 'course', 'assessment', 'attempt_number')},
        ),
    ]
