# Generated by Django 4.2.11 on 2026-09-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0011_merge_20260814_1107'),
        ('assessments_app', '0014_assessment_draft_attachments'),
    ]

    operations = [
    ]
