# Generated by Django 4.2.11 on 2026-09-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0015_merge_20260902_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='module',
        ),
    ]
