# Generated by Django 6.0.3 on 2026-09-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0018_assessment_links_set_null'),
        ('assessments_app', '0019_alter_assessment_course_alter_assessment_module'),
    ]

    operations = [
    ]
