# Generated by Django 4.2.11 on 2026-09-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments_app', '0020_merge_20260910_1547'),
        ('assessments_app', '0021_attempt_assessment_snapshot'),
    ]

    operations = [
    ]
